# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-creds
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:Slca6HpCLDo=,iv:62jLf0mSNtQLHHN4Zv1YZU9TQcj/QuvlHIp1tytxNgU=,tag:0oU1LMKSmSZK1D+E6bWKQA==,type:str]
    admin-password: ENC[AES256_GCM,data:FrGKUuUgzcV2,iv:GpTnkAnXcM3uLo9JWgYq87HgleD6+jck8Hny0ZLkf8E=,tag:KoxE425mfPJvvJQRVNxlyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xcngmepv707dkgxnl4uj0heupajdfuturgv7q7fd5jvkar9zsv5sgrvc3r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWHYyNmh5cW1DVzVsazRw
            SkpGLzJvVzNudzh3clYvMHZKOXU3dG0yb3l3CjVBV3dwSlVPcGpiNEw0M2poQUxY
            RkJqNDZWM25oc2Vka0Z3MFo1UzlhR28KLS0tIGtaZXRpL1Uwd1hldFJjUGxTTTZu
            UDZ6YTBOb2ltT2lNTzJxUzFBWUVxeXMK2bO0I1cpUK/nSH0E48mciSdrgw4V9qAd
            qFJllHDtZEO9nYl3kt1CLQ1EFGo0ANoLqBnGwqj1Zp6RIJxF+fM8aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-18T20:27:51Z"
    mac: ENC[AES256_GCM,data:U50PIm7Q9/WSbe9zU+YiwyWiNyfPdjtRDfgFugUtgC8YTNrr00UiIrfwaqBMrgalIvpSm1Tdho5ZFSuGIb1r6bdkyrfvC5+Lt9nWfj482bRhJaAbRhjw3Lrv8ujK5rizbuSZlsgHXerb0gza6kXPY4Ql4Mj0EBKpfbSqeIyh5OE=,iv:RIhZXpnZv2NNIE1Mu2qkEoSwD54JTip69BXAR71qyKU=,tag:wBDhtcr+UMH328bzqRAhSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
