---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1xcngmepv707dkgxnl4uj0heupajdfuturgv7q7fd5jvkar9zsv5sgrvc3r
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1xcngmepv707dkgxnl4uj0heupajdfuturgv7q7fd5jvkar9zsv5sgrvc3r
