---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-blueiris
  namespace: networking
  annotations:
    external-dns.alpha.kubernetes.io/target: "home.${SECRET_ROOT_DOMAIN}"
    external-dns/is-public: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  ingressClassName: "traefik"
  rules:
    - host: blueiris.${SECRET_ROOT_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: external-blueiris
                port:
                  number: 81
    - host: blueiris.home.${SECRET_ROOT_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: external-blueiris
                port:
                  number: 81
    - host: blueiris.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: external-blueiris
                port:
                  number: 81
---
apiVersion: v1
kind: Service
metadata:
  name: external-blueiris
  namespace: networking
spec:
  ports:
    - name: http
      port: 81
  type: ExternalName
  externalName: 192.168.2.100
