---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-blueiris
  namespace: networking
  annotations:
    #cert-manager.io/cluster-issuer: "letsencrypt-production"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  ingressClassName: "traefik"
  tls:
    - hosts:
        - blueiris.${SECRET_DOMAIN}
      #secretName: external-blueiris-tls
      #secretName omitted to use default wildcard certificate
  rules:
  - host: blueiris.${SECRET_DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-blueiris
            port:
              number: 81
---
apiVersion: v1
kind: Service
metadata:
  name: external-blueiris
  namespace: networking
spec:
  ports:
  - name: http
    port: 81
  type: ExternalName
  externalName: 192.168.2.100
