---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 13.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.6.7
    env:
      TZ: "${TIMEZONE}"
    envFrom:
      - secretRef:
          name: home-assistant-secrets
    service:
      main:
        type: LoadBalancer
        loadBalancerIP:: "${METALLB_HOME_ASSISTANT_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123
        # annotations:
        #   metallb.universe.tf/allow-shared-ip: home-assistant
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
        #  external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        #  external-dns/is-public: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1
    metrics:
      enabled: false
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    # probes:
    #   liveness:
    #     enabled: false
    #   readiness:
    #     enabled: false
    #   startup:
    #     enabled: false
    # mariadb:
    #   enabled: true
    #   image:
    #     repository: bitnami/mariadb
    #     tag: 10.6.7-debian-10-r70
    #   architecture: standalone
    #   auth:
    #     database: home-assistant
    #     username: home-assistant
    #     password: home-assistant-pass
    #     rootPassword: home-assistantrootpass
    #     existingSecret:
    #   primary:
    #     persistence:
    #       enabled: true
    #       storageClass: cstor-csi-disk
    # postgresql:
    #   enabled: false
    podAnnotations:
      secret.reloader.stakater.com/reload: home-assistant-secrets
    addons:
      codeserver:
        enabled: true
        image:
          repository: docker.io/codercom/code-server
          tag: 4.4.0
        env:
          TZ: "${TIMEZONE}"
        workingDir: "/config"
        # git:
        #   deployKeySecret: home-assistant-code-server-secret
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
          hosts:
            - host: "hass-code.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
        volumeMounts:
          - name: config
            mountPath: /config
    resources:
      requests:
        cpu: 100m
        memory: 1000Mi
      limits:
        memory: 2500Mi
