---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: nzbget
      version: 12.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/k8s-at-home/nzbget
      tag: v21.1
    env:
      TZ: "${TIMEZONE}"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: "nzbget.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        storageClass: cstor-csi-disk
        size: 30Gi
        #existingClaim: nzbget-config-v1
      downloads:
        enabled: true
        existingClaim: nfs-media-pvc
        subPath: Downloads
        #mountPath: /data
        #readOnly: false
    resources:
      requests:
        cpu: 25m
        memory: 300Mi
      limits:
        memory: 1000Mi
