---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: openebs-jiva
  namespace: flux-system
spec:
  interval: 15m
  url: https://openebs.github.io/jiva-operator
  timeout: 3m
