kubernetes:
  children:
    master:
      hosts:
        k3s-master-0:
          ansible_host: 192.168.2.85
        k3s-master-1:
          ansible_host: 192.168.2.86
        k3s-master-2:
          ansible_host: 192.168.2.77
    worker:
      hosts:
        k3s-node-1:
          ansible_host: 192.168.2.87
        k3s-node-2:
          ansible_host: 192.168.2.75
        k3s-node-3:
          ansible_host: 192.168.2.76
