---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  #name: &app esphome
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: esphome
      version: 8.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  # chart:
  #   spec:
  #     chart: kah-common-chart
  #     version: 1.1.2
  #     sourceRef:
  #       kind: HelmRepository
  #       name: k8s-at-home-charts
  #       namespace: flux-system
  #     interval: 15m
  install:
    createNamespace: true
  values:
    #global:
    #  nameOverride: *app
    image:
      repository: ghcr.io/esphome/esphome
      tag: 2022.5.1
    env:
      TZ: "${TIMEZONE}"
      ESPHOME_DASHBOARD_USE_PING: "true"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    #envFrom:
    #  - secretRef:
    #      name: esphome-secrets
    #service:
    #  main:
    #    ports:
    #      http:
    #        port: 6052
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
        #  external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        #  external-dns/is-public: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: "esphome.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        storageClass: cstor-csi-disk
    #    existingClaim: esphome-config-v1
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
      limits:
        memory: 1000Mi
