# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:+ksxWPrkKrpVnLN3QhVOnof8U08qSHY0JiggdxokGFi7mNhcDK1WAg==,iv:g+rCeMoWqIsrv6g5rzPeLWrsWglVX9B7pHHUeMdN2vM=,tag:OtOtn/ov93Mk8IXEht0qoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xcngmepv707dkgxnl4uj0heupajdfuturgv7q7fd5jvkar9zsv5sgrvc3r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWHYyNmh5cW1DVzVsazRw
            SkpGLzJvVzNudzh3clYvMHZKOXU3dG0yb3l3CjVBV3dwSlVPcGpiNEw0M2poQUxY
            RkJqNDZWM25oc2Vka0Z3MFo1UzlhR28KLS0tIGtaZXRpL1Uwd1hldFJjUGxTTTZu
            UDZ6YTBOb2ltT2lNTzJxUzFBWUVxeXMK2bO0I1cpUK/nSH0E48mciSdrgw4V9qAd
            qFJllHDtZEO9nYl3kt1CLQ1EFGo0ANoLqBnGwqj1Zp6RIJxF+fM8aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-11T00:43:40Z"
    mac: ENC[AES256_GCM,data:UHN62Mv+SEgXHhzB/AFQZGoTN7XR8BT22NnIk+2BKV+NrDUpuRBBEHPlsqgGkMzj2fnoXbcYLe+4BLo8zRQI3eauZ5LYViCcisENA1U5rgP8MICQy+GEQkW+XUKNgeyvqqvWB78e4dxU2Xp9KMhsS3gxU+Wx8F7nsuO0TCXHx2Q=,iv:UwuZNG7Y5tmwP5CBh4PXmru8hsH6D0B5OpgDnUkzRr0=,tag:a77c5ROklGvCRqv/+kJD/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
