---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: overseerr
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: 1.29.1
    env:
      TZ: "${TIMEZONE}"
      LOG_LEVEL: "info"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/target: "home.${SECRET_ROOT_DOMAIN}"
          external-dns/is-public: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        #  traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: "requests.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
          - host: "plexrequests.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
          - host: "requests.${SECRET_ROOT_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
          - host: "plexrequests.${SECRET_ROOT_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        # tls:
        #   - secretName: overseerr-tls
        #     hosts:
        #       - "requests.${SECRET_DOMAIN}" 
        #       - "plexrequests.${SECRET_DOMAIN}" 
        #       - "requests.${SECRET_ROOT_DOMAIN}" 
        #       - "plexrequests.${SECRET_ROOT_DOMAIN}" 
    persistence:
      config:
        enabled: true
        storageClass: cstor-csi-disk
        size: 1Gi
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 500Mi