---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nut-master
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: network-ups-tools
      version: 6.3.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: ghcr.io/k8s-at-home/network-ups-tools
      tag: v2.8.0
    securityContext:
      privileged: true
    controllerType: daemonset
    tolerations:
      # - key: "thin-client"
      - effect: NoSchedule
        operator: "Exists"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-ups
                  operator: In
                  values:
                    - "true"
    service:
      main:
        ports:
          http:
            enabled: false
          server:
            enabled: true
            protocol: TCP
            port: 3493
        type: LoadBalancer
        loadBalancerIP: "${METALLB_NUT_ADDR}"
        externalTrafficPolicy: Local
    # The main configuration files for network-ups-tools
    config:
      # If set to 'values', the configuration will be read from these values.
      # Otherwise you have to mount a volume to /etc/nut containing the configuration files.
      mode: values
      # See https://github.com/networkupstools/nut/tree/master/conf for config sample files
      files:
        nut.conf: |
          MODE=netserver

        ups.conf: |
          [ups-1]
            driver = usbhid-ups
            port = auto
            # pollinterval = 15
            desc = APC Back-UPS Pro 1500

        upsd.conf: |
          LISTEN 0.0.0.0

        upsd.users: |
          [admin]
            password = secret
            actions = SET
            instcmds = ALL
            upsmon master
          [upsmon]
            password = secret
            upsmon slave

        upsmon.conf: |
          MONITOR ups-1@localhost 1 admin secret master

    resources:
      requests:
        memory: 64Mi
        cpu: 25m
      limits:
        memory: 128Mi
    persistence:
      ups:
        enabled: true
        type: hostPath
        # -- The path of the usb ups on the host.
        hostPath: /dev/usb/hiddev0
        # /dev/bus/usb/001/005
        # -- Optional path for ups to mount in the container.
        mountPath: /dev/usb/hiddev0
        # /dev/bus/usb/001/001
        readOnly: false
    metrics:
      enabled: true
      serviceMonitor:
        interval: 15s
        scrapeTimeout: 10s
      prometheusRule:
        enabled: true
