---
apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: exports
  namespace: kasten-io
spec:
  locationSpec:
    type: FileStore
    fileStore:
      claimName: nfs-backup-k10-pvc
      path: exports
    credential:
      secretType: ""
      secret:
        apiVersion: ""
        kind: ""
        name: ""
        namespace: ""
  type: Location
