---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-backup-k10-pv
spec:
  storageClassName: nfs-backup-k10
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NAS_ADDR}"
    path: /mnt/vol2/Backup/k10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-backup-k10-pvc
  namespace: kasten-io
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-backup-k10
  resources:
    requests:
      storage: 1Mi
