---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwavejs2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: zwavejs2mqtt
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  dependsOn:
    - name: node-feature-discovery
      namespace: kube-system
  values:
    image:
      repository: ghcr.io/zwave-js/zwavejs2mqtt
      tag: 6.9.1
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 8091
          websocket:
            enabled: true
            port: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: "zwave.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    securityContext:
      privileged: true
    persistence:
      config:
        enabled: true
        storageClass: cstor-csi-disk
        mountPath: "/usr/src/app/store"
        size: 1Gi
        skipuninstall: true
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C0F0071D-if00-port0
        hostPathType: CharDevice
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-zwave
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "thin-client"
        operator: "Exists"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 500Mi
