# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:VSGcfIVpDv5IGmggPF28YlFP4LrF8Q==,iv:hpkGZHu1uzmZTR0eL0bn1w22W1ip5XB5hyQUV5n/v08=,tag:AgwJXK1LjrkqysCaonnLrA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:tXKhOMiWvdSvh4VbfA3hKGH0QCUv/9Pi,iv:Rf/d0iRi1e5j/uxe4Jc+syqyX0CrtM6mqicF9CNdMUs=,tag:J3gHoViuOe5JldKe8da0iQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xcngmepv707dkgxnl4uj0heupajdfuturgv7q7fd5jvkar9zsv5sgrvc3r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL0dEMUNEYTJsZXhSR1FI
            eTExWTVRazJuWlRLNjRsSkY0MnNENkNkZUNrCms2RjZvajRPUURpbmhoWWdSNjhU
            TmVVbm91aUhOWTRBN2Q4ZVNUbnJickkKLS0tIDZKZk1jcFJCZlUxSTFLODAvcTA5
            aFZoWWozRks3aDUwanpQanRGNG55YTAK78zzVPikMVd+Lw6W6ySD5utOFM65uAKK
            dVyYa7NeAQjTL9/p/XMt3HEkysHnyi7740zb3k9jfvPy6OSNBFWjkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-10T23:46:38Z"
    mac: ENC[AES256_GCM,data:8VmH/DEj4Z5dF00k3HDpObskk/WsZ3i+DLg/zjFefUr7eWw8IyTqfqtcJR+oMRbZX1ymil//uxKq2dCEEoqjqjKgoO+9JWgp2bebarASVcsXffDQonkgAASHjOC3TTtSJbOW//YLc7w6pGpQv4Z0QzEcQBiHmZyiJPo3ootblRQ=,iv:DrH7IxjhesBEhajRufl6yFCBwT8rpJEvNWn3xtkaBUA=,tag:0YgiiePJhXi6HIIGp2mvDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
