---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - home
  - kasten-io
  - kube-system
  - media
  - monitoring
  - networking
  # - security
  - system-upgrade
