kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: backup-all-pvc
  namespace: kasten-io
spec:
  comment: Policy to backup all resources daily.  Daily snapshot/backup
  frequency: "@daily"
  subFrequency:
    minutes:
      - 0
    hours:
      - 17
    weekdays:
      - 0
    days:
      - 1
    months:
      - 1
  retention:
    daily: 7
    weekly: 4
    monthly: 12
    yearly: 7
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - home
          - media
          - security
  actions:
    - action: backup
      backupParameters:
        filters:
          includeResources:
            - resource: persistentvolumeclaims
              matchExpressions:
                - key: kasten.io/backup-volume
                  operator: In
                  values:
                    - enabled
        profile:
          name: all-pvc
          namespace: kasten-io
    - action: export
      exportParameters:
        frequency: "@daily"
        profile:
          name: all-pvc
          namespace: kasten-io
        exportData:
          enabled: true
      retention: {}