---
kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: daily-export
  namespace: kasten-io
spec:
  actions:
    - action: backup
      backupParameters:
        profile:
          name: exports
          namespace: kasten-io
        filters:
          includeResources: []
          excludeResources:
            - group: ""
              version: ""
              resource: persistentvolumeclaims
              name: nfs-media-pvc
              matchExpressions: []
    - action: export
      exportParameters:
        frequency: "@daily"
        profile:
          name: exports
          namespace: kasten-io
        exportData:
          enabled: true
  frequency: '@daily'
  subFrequency:
    minutes:
      - 0
    hours:
      - 5
    weekdays:
      - 0
    days:
      - 1
    months:
      - 1
  retention:
    daily: 2
    monthly: 1
    weekly: 1
    yearly: 1
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - home
          - media
