---
kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: hourly-backup
  namespace: kasten-io
spec:
  actions:
    - action: backup
      backupParameters:
        profile:
          name: exports
          namespace: kasten-io
        filters:
          includeResources: []
          excludeResources:
            - group: ""
              version: ""
              resource: persistentvolumeclaims
              name: nfs-media-pvc
              matchExpressions: []
  frequency: '@hourly'
  retention:
    hourly: 4
    daily: 0
    monthly: 0
    weekly: 0
    yearly: 0
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - home
          - media