---
kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: media
  namespace: kasten-io
spec:
  actions:
    - action: backup
      backupParameters:
        profile:
          name: media
          namespace: kasten-io
  frequency: '@hourly'
  retention:
    hourly: 4
    daily: 1
    monthly: 1
    weekly: 1
    yearly: 1
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - media