---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "wildcard-${SECRET_ROOT_DOMAIN/./-}"
  namespace: networking
spec:
  secretName: "wildcard-${SECRET_ROOT_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_ROOT_DOMAIN}"
  dnsNames:
    - "${SECRET_ROOT_DOMAIN}"
    - "*.${SECRET_ROOT_DOMAIN}"
    - "*.home.${SECRET_ROOT_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
