---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lidarr
  - nfs-media-pv.yaml
  - nzbget
  - overseerr
  - plex
  - prowlarr
  - radarr
  - readarr
  - sonarr
  - trunk-recorder
  # - tubesync
  - youtubedl
