---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  releaseName: k10
  interval: 15m
  chart:
    spec:
      chart: k10
      version: 4.5.15
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    eula:
      accept: true
      company: personal
      email: jp83@users.noreply.github.com
    global:
      persistence:
        storageClass: cstor-csi-disk
    auth:
      tokenAuth:
        enabled: true
    clusterName: k3s-home
    ingress:
      create: true
      class: traefik
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
      host: &host "k10.${SECRET_DOMAIN}"
      urlPath: k10
      #pathType: Prefix
      #hosts:
      #    - host: "k10.${SECRET_DOMAIN}"
      #      paths:
      #        - path: /
      #          pathType: Prefix
      hosts:
        - *host
      #tls:
      #  enabled: true
      #  secretName: "${SECRET_PUBLIC_DOMAIN/./-}-tls"
    grafana:
      enabled: false